language: java
jdk:
- openjdk8
script: mvn clean install
notifications:
  slack:
    secure: lOzprTB0Yng4nHBi/E9ncSHOYytU91sG64lMc4eP4JDh2/UUHta6mUcFmjYEJY+T4UOQ6DHVFygU/YLvSuE7QUjGxXLunx6ywIrf8Ks+DIB/xF/N/b4CymYbJPoBr7d4/bUiv3t/QhYStgNOoyD7eWGEjcpMVuBjUp7fbUZx7T/FTFpkT2MCjPVg8pVBmEwMkZUJx2j+W1LRr0m4CQbMrv1SGJhVWgrBPkOFFxa4/m+tjLf1Za9sCVyEadqmmbrzHxICBSagucqZ0YLFwReCouIFGmLGO0Felsm+lBPnPHronK3u5E56bDZwOYmyFFiH48pBywDWuW2RlxRnKLi1xgth6GglEnpwq1wjxn1lhDUAzaYDVLf8E3jH44rcqPRZhgTSCeDGO75eMZebuBcabyUqETz7cqL5EalTHdLxlhWzeFQEv2JCkY+/i0TGzNiCEvcYIUYA/c2ZoNOpbcY2DxnocCg2ethFv0QfcFJ2VpdL2UWRj0RfITL9vhNMMoY+CpfpJEUNQmwP9iBwk+350wEcDce682QT7Nh/P88OmuNIZFMhRkohn4ZFIahyhB4cElJnMZ0DobjF/rGPJQbVNm2jWPf4lkgK+rTxCRqInOM4RokT7mfXY/aacSur3GQwJLtOq5jfdURyxpkkDTg5GC3+jppk9bBWY//ZOCxXCAg=
